export const GET_PATIENTS_LOADING = 'GET_PATIENTS_LOADING';
export const GET_PATIENTS_SUCCESS = 'GET_PATIENTS_SUCCESS';
export const GET_PATIENTS_FAIL = 'GET_PATIENTS_FAIL';

export const GET_APPOINTMENTS_LOADING = 'GET_APPOINTMENTS_LOADING';
export const GET_APPOINTMENTS_SUCCESS = 'GET_APPOINTMENTS_SUCCESS';
export const GET_APPOINTMENTS_FAIL = 'GET_APPOINTMENTS_FAIL';

// export const CREATE_CONTACT_LOADING = 'CREATE_CONTACT_LOADING';
// export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
// export const CREATE_CONTACT_FAIL = 'CREATE_CONTACT_FAIL';
//
// export const DELETE_CONTACT_LOADING = 'DELETE_CONTACT_LOADING';
// export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
// export const DELETE_CONTACT_FAIL = 'DELETE_CONTACT_FAIL';
//
// export const EDIT_CONTACT_LOADING = 'EDIT_CONTACT_LOADING';
// export const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS';
// export const EDIT_CONTACT_FAIL = 'EDIT_CONTACT_FAIL';

export interface IActions {
    GET_PATIENTS_LOADING: string;
    GET_PATIENTS_SUCCESS: string;
    GET_PATIENTS_FAIL: string;

    GET_APPOINTMENTS_LOADING: string;
    GET_APPOINTMENTS_SUCCESS: string;
    GET_APPOINTMENTS_FAIL: string;
}
