export const GET_PATIENTS_LOADING = 'GET_PATIENTS_LOADING';
export const GET_PATIENTS_SUCCESS = 'GET_PATIENTS_SUCCESS';
export const GET_PATIENTS_FAIL = 'GET_PATIENTS_FAIL';

export const GET_PATIENT_LOADING = 'GET_PATIENT_LOADING';
export const GET_PATIENT_SUCCESS = 'GET_PATIENT_SUCCESS';
export const GET_PATIENT_FAIL = 'GET_PATIENT_FAIL';

// export const CREATE_CONTACT_LOADING = 'CREATE_CONTACT_LOADING';
// export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
// export const CREATE_CONTACT_FAIL = 'CREATE_CONTACT_FAIL';
//
// export const DELETE_CONTACT_LOADING = 'DELETE_CONTACT_LOADING';
// export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
// export const DELETE_CONTACT_FAIL = 'DELETE_CONTACT_FAIL';
//
// export const EDIT_CONTACT_LOADING = 'EDIT_CONTACT_LOADING';
// export const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS';
// export const EDIT_CONTACT_FAIL = 'EDIT_CONTACT_FAIL';
